server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 120m

picture:
  info:
    address: D:\code\picture\productInfo
  product:
    address: D:\code\picture\product

spring:
  profiles:
    active: #spring.profiles.active#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 6000
      max-lifetime: 300000
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 0
  jpa:
    hibernate:
      #更新或创建数据库表结构
      ddl-auto: update
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #输出执行sql
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/,file:${picture.info.address},file:${picture.product.address},
  mvc:
    static-path-pattern: /**

jwt:
  expiration: 86400000
  secret: WECHAT_MALL
  tokenHead: "Bearer "

wechat:
  micro-program:
  pay:
