spring:
  profiles:
    include: devConn

logging:
  file: logs/mall.dev.log
  level:
    root: info

wechat:
  micro-program:
  pay:
    url:
      unified-order: https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder
      order-query: https://api.mch.weixin.qq.com/sandboxnew/pay/orderquery
      close-order: https://api.mch.weixin.qq.com/sandboxnew/pay/closeorder

